version: 2

sources:
  - name: googles_analytics_4
    schema: google_analytics_4
    tables:
      - name: events_20210131
      
  - name: google_sheets
    schema: google_sheets
    tables:
      - name: account_manager_region_mapping

  - name: dataset_local_bike
    schema: dataset_local_bike
    tables:
      - name: brands
      - name: categories
      - name: products
      - name: orders
      - name: order_items
      - name: customers
      - name: staffs
      - name: stocks
      - name: stores

